# AIM :Can you predict a rider's taxi fare?

importing libraries

In [5]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline
from sklearn.model_selection import train_test_split

loading dataset

In [6]:
taxi_df = pd.read_csv('/content/drive/MyDrive/TaxiFare.csv')
taxi_df

,unique_id,amount,date_time_of_pickup,longitude_of_pickup,latitude_of_pickup,longitude_of_dropoff,latitude_of_dropoff,no_of_passenger
0,26:21.0,4.5,2009-06-15 17:26:21 UTC,-73.844311,40.721319,-73.841610,40.712278,1
1,52:16.0,16.9,2010-01-05 16:52:16 UTC,-74.016048,40.711303,-73.979268,40.782004,1
2,35:00.0,5.7,2011-08-18 00:35:00 UTC,-73.982738,40.761270,-73.991242,40.750562,2
3,30:42.0,7.7,2012-04-21 04:30:42 UTC,-73.987130,40.733143,-73.991567,40.758092,1
4,51:00.0,5.3,2010-03-09 07:51:00 UTC,-73.968095,40.768008,-73.956655,40.783762,1
...,...,...,...,...,...,...,...,...
49995,25:15.0,15.0,2013-06-12 23:25:15 UTC,-73.999973,40.748531,-74.016899,40.705993,1
49996,19:18.0,7.5,2015-06-22 17:19:18 UTC,-73.984756,40.768211,-73.987366,40.760597,1
49997,53:00.0,6.9,2011-01-30 04:53:00 UTC,-74.002698,40.739428,-73.998108,40.759483,1
49998,09:00.0,4.5,2012-11-06 07:09:00 UTC,-73.946062,40.777567,-73.953450,40.779687,2
49999,13:14.0,10.9,2010-01-13 08:13:14 UTC,-73.932603,40.763805,-73.932603,40.763805,1

checking dataset

In [7]:
taxi_df.head(10)

,unique_id,amount,date_time_of_pickup,longitude_of_pickup,latitude_of_pickup,longitude_of_dropoff,latitude_of_dropoff,no_of_passenger
0,26:21.0,4.5,2009-06-15 17:26:21 UTC,-73.844311,40.721319,-73.841610,40.712278,1
1,52:16.0,16.9,2010-01-05 16:52:16 UTC,-74.016048,40.711303,-73.979268,40.782004,1
2,35:00.0,5.7,2011-08-18 00:35:00 UTC,-73.982738,40.761270,-73.991242,40.750562,2
3,30:42.0,7.7,2012-04-21 04:30:42 UTC,-73.987130,40.733143,-73.991567,40.758092,1
4,51:00.0,5.3,2010-03-09 07:51:00 UTC,-73.968095,40.768008,-73.956655,40.783762,1
5,50:45.0,12.1,2011-01-06 09:50:45 UTC,-74.000964,40.731630,-73.972892,40.758233,1
6,35:00.0,7.5,2012-11-20 20:35:00 UTC,-73.980002,40.751662,-73.973802,40.764842,1
7,22:00.0,16.5,2012-01-04 17:22:00 UTC,-73.951300,40.774138,-73.990095,40.751048,1
8,10:00.0,9.0,2012-12-03 13:10:00 UTC,-74.006462,40.726713,-73.993078,40.731628,1
9,11:00.0,8.9,2009-09-02 01:11:00 UTC,-73.980658,40.733873,-73.991540,40.758138,2

In [8]:
taxi_df.shape

(50000, 8)

In [9]:
taxi_df.describe()

,amount,longitude_of_pickup,latitude_of_pickup,longitude_of_dropoff,latitude_of_dropoff,no_of_passenger
count,50000.000000,50000.000000,50000.000000,50000.000000,50000.000000,50000.000000
mean,11.364171,-72.509756,39.933759,-72.504616,39.926251,1.667840
std,9.685557,10.393860,6.224857,10.407570,6.014737,1.289195
min,-5.000000,-75.423848,-74.006893,-84.654241,-74.006377,0.000000
25%,6.000000,-73.992062,40.734880,-73.991152,40.734372,1.000000
50%,8.500000,-73.981840,40.752678,-73.980082,40.753372,1.000000
75%,12.500000,-73.967148,40.767360,-73.963584,40.768167,2.000000
max,200.000000,40.783472,401.083332,40.851027,43.415190,6.000000

In [10]:
taxi_df.sample(15)

,unique_id,amount,date_time_of_pickup,longitude_of_pickup,latitude_of_pickup,longitude_of_dropoff,latitude_of_dropoff,no_of_passenger
43150,24:00.0,13.30,2012-06-09 19:24:00 UTC,-73.980985,40.733422,-74.001650,40.761177,1
10002,26:01.0,0.00,2010-02-15 14:26:01 UTC,-73.987115,40.738808,-74.005911,40.713960,1
13357,53:00.0,9.50,2014-11-04 15:53:00 UTC,-73.973662,40.764135,-73.987187,40.749297,1
41344,45:00.0,12.00,2014-12-17 14:45:00 UTC,-73.995498,40.739148,-73.982543,40.727455,1
6494,28:24.0,8.90,2011-02-15 16:28:24 UTC,-73.975329,40.762502,-73.987845,40.738445,1
4453,49:00.0,7.70,2009-10-05 20:49:00 UTC,-73.978470,40.745020,-73.959115,40.764083,1
32275,49:00.0,4.90,2011-07-17 10:49:00 UTC,-73.963380,40.793627,-73.951210,40.785907,2
45100,49:00.0,32.27,2010-11-22 16:49:00 UTC,-73.953513,40.775358,-73.872600,40.774400,2
15451,01:26.0,4.10,2010-11-08 09:01:26 UTC,-73.985070,40.747994,-73.991789,40.738264,1
23835,06:00.0,6.50,2010-08-14 01:06:00 UTC,-73.991447,40.726860,-74.000183,40.742825,1
45540,20:15.0,5.50,2013-05-13 07:20:15 UTC,-73.994280,40.750141,-73.985504,40.760480,1
38671,52:00.0,3.70,2012-02-03 14:52:00 UTC,-73.982533,40.771647,-73.987762,40.767117,1
16601,12:34.0,6.90,2011-09-07 23:12:34 UTC,-73.991181,40.749852,-73.987392,40.756031,2
4018,09:00.0,9.50,2013-01-23 17:09:00 UTC,-73.957392,40.770547,-73.974647,40.753902,6
12937,14:47.0,10.90,2012-05-18 09:14:47 UTC,-73.982978,40.739739,-73.978243,40.762940,1

In [11]:
taxi_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50000 entries, 0 to 49999
Data columns (total 8 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   unique_id             50000 non-null  object
 1   amount                50000 non-null  float64
 2   date_time_of_pickup   50000 non-null  object
 3   longitude_of_pickup   50000 non-null  float64
 4   latitude_of_pickup    50000 non-null  float64
 5   longitude_of_dropoff  50000 non-null  float64
 6   latitude_of_dropoff   50000 non-null  float64
 7   no_of_passenger       50000 non-null  int64
dtypes: float64(5), int64(1), object(2)
memory usage: 3.1+ MB

data cleaning

In [42]:
taxi_df.isnull().sum()

amount                  0
longitude_of_pickup     0
latitude_of_pickup      0
longitude_of_dropoff    0
latitude_of_dropoff     0
no_of_passenger         0
dtype: int64

In [43]:
taxi_df.head(20)

,amount,longitude_of_pickup,latitude_of_pickup,longitude_of_dropoff,latitude_of_dropoff,no_of_passenger
0,4.5,-73.844311,40.721319,-73.841610,40.712278,1
1,16.9,-74.016048,40.711303,-73.979268,40.782004,1
2,5.7,-73.982738,40.761270,-73.991242,40.750562,2
3,7.7,-73.987130,40.733143,-73.991567,40.758092,1
4,5.3,-73.968095,40.768008,-73.956655,40.783762,1
5,12.1,-74.000964,40.731630,-73.972892,40.758233,1
6,7.5,-73.980002,40.751662,-73.973802,40.764842,1
7,16.5,-73.951300,40.774138,-73.990095,40.751048,1
8,9.0,-74.006462,40.726713,-73.993078,40.731628,1
9,8.9,-73.980658,40.733873,-73.991540,40.758138,2
10,5.3,-73.996335,40.737142,-73.980721,40.733559,1
11,5.5,0.000000,0.000000,0.000000,0.000000,3
12,4.1,-73.991601,40.744712,-73.983081,40.744682,2
13,7.0,-74.005360,40.728867,-74.008913,40.710907,1
14,7.7,-74.001821,40.737547,-73.998060,40.722788,2
15,5.0,0.000000,0.000000,0.000000,0.000000,1
16,12.5,-73.986430,40.760465,-73.988990,40.737075,1
17,5.3,-73.981060,40.737690,-73.994177,40.728412,1
18,5.3,-73.969505,40.784843,-73.958732,40.783357,1
19,4.0,-73.979815,40.751902,-73.979446,40.755481,1

we found that there are no null values but still having zeroes in it

In [12]:
mean2 = taxi_df["longitude_of_pickup"].mean()
taxi_df["longitude_of_pickup"] = taxi_df["longitude_of_pickup"].replace(np.nan,mean2)

In [13]:
mean3 = taxi_df["latitude_of_pickup"].mean()
taxi_df["latitude_of_pickup"] = taxi_df["latitude_of_pickup"].replace(np.nan,mean3)

In [14]:
mean4 = taxi_df["longitude_of_dropoff"].mean()
taxi_df["longitude_of_dropoff"] = taxi_df["longitude_of_dropoff"].replace(np.nan,mean4)

In [15]:
mean5 = taxi_df["latitude_of_dropoff"].mean()
taxi_df["latitude_of_dropoff"] = taxi_df["latitude_of_dropoff"].replace(np.nan,mean5)

In [16]:
taxi_df.head(15)

,unique_id,amount,date_time_of_pickup,longitude_of_pickup,latitude_of_pickup,longitude_of_dropoff,latitude_of_dropoff,no_of_passenger
0,26:21.0,4.5,2009-06-15 17:26:21 UTC,-73.844311,40.721319,-73.841610,40.712278,1
1,52:16.0,16.9,2010-01-05 16:52:16 UTC,-74.016048,40.711303,-73.979268,40.782004,1
2,35:00.0,5.7,2011-08-18 00:35:00 UTC,-73.982738,40.761270,-73.991242,40.750562,2
3,30:42.0,7.7,2012-04-21 04:30:42 UTC,-73.987130,40.733143,-73.991567,40.758092,1
4,51:00.0,5.3,2010-03-09 07:51:00 UTC,-73.968095,40.768008,-73.956655,40.783762,1
5,50:45.0,12.1,2011-01-06 09:50:45 UTC,-74.000964,40.731630,-73.972892,40.758233,1
6,35:00.0,7.5,2012-11-20 20:35:00 UTC,-73.980002,40.751662,-73.973802,40.764842,1
7,22:00.0,16.5,2012-01-04 17:22:00 UTC,-73.951300,40.774138,-73.990095,40.751048,1
8,10:00.0,9.0,2012-12-03 13:10:00 UTC,-74.006462,40.726713,-73.993078,40.731628,1
9,11:00.0,8.9,2009-09-02 01:11:00 UTC,-73.980658,40.733873,-73.991540,40.758138,2
10,30:50.0,5.3,2012-04-08 07:30:50 UTC,-73.996335,40.737142,-73.980721,40.733559,1
11,24:00.0,5.5,2012-12-24 11:24:00 UTC,0.000000,0.000000,0.000000,0.000000,3
12,04:03.0,4.1,2009-11-06 01:04:03 UTC,-73.991601,40.744712,-73.983081,40.744682,2
13,54:00.0,7.0,2013-07-02 19:54:00 UTC,-74.005360,40.728867,-74.008913,40.710907,1
14,11:05.0,7.7,2011-04-05 17:11:05 UTC,-74.001821,40.737547,-73.998060,40.722788,2

In [17]:
 taxi_df.drop(['date_time_of_pickup'],axis=1,inplace=True)

In [18]:
taxi_df.drop(['unique_id'],axis=1,inplace=True)

In [19]:
taxi_df.sample(10)

,amount,longitude_of_pickup,latitude_of_pickup,longitude_of_dropoff,latitude_of_dropoff,no_of_passenger
16449,6.5,-73.996848,40.744625,-73.983682,40.744735,3
32788,7.3,-73.978026,40.758765,-73.982267,40.771015,2
11240,6.9,-73.962051,40.779048,-73.984576,40.776826,1
5607,5.0,-74.001460,40.746791,-74.001096,40.739932,1
39917,10.0,-73.962458,40.758778,-73.976708,40.732443,4
39753,16.0,-73.998351,40.723081,-73.970788,40.766963,2
15987,12.1,-73.954018,40.770768,-73.982878,40.727030,2
45854,13.0,-73.973972,40.743082,-73.985453,40.752627,1
6416,6.1,-73.137393,41.366138,-73.137393,41.366138,1
38641,14.0,-73.983275,40.741347,-73.992920,40.729952,1

modals implementation

In [20]:
x = taxi_df.drop(columns=['amount'],axis=1)
y = taxi_df['amount']

In [21]:
x_train, x_test, y_train,y_test = train_test_split(x, y, test_size=0.3, random_state=1)

In [22]:
from sklearn.ensemble import GradientBoostingRegressor

In [23]:
model_1 = GradientBoostingRegressor()

In [24]:
model_1.fit(x_train,y_train)

GradientBoostingRegressor()

In [25]:
s1 = model_1.score(x_train,y_train)
print("After GradientBoostingRegressor train score are: ",s1)

After GradientBoostingRegressor train score are:  0.7441405403638608

In [26]:
s1 = model_1.score(x_test,y_test)
print("After GradientBoostingRegressor train score are: ",s1)

After GradientBoostingRegressor train score are:  0.6914475533046602

In [27]:
from sklearn.tree import DecisionTreeRegressor

In [28]:
model_2 = DecisionTreeRegressor()

In [29]:
model_2.fit(x_train,y_train)

DecisionTreeRegressor()

In [30]:
s2 = model_2.score(x_train,y_train)
print("After Decision TreeRegressor train score are: ",s2)

After Decision TreeRegressor train score are:  0.9763906952071122

In [31]:
s2 = model_2.score(x_test,y_test)
print("After Decision TreeRegressor train score are: ",s2)

After Decision TreeRegressor train score are:  0.519322607866394

In [32]:
from sklearn.ensemble import RandomForestRegressor

In [33]:
model_3 = RandomForestRegressor()

In [34]:
model_3.fit(x_train,y_train)

RandomForestRegressor()

In [35]:
s3 = model_3.score(x_train,y_train)
print("After RandomForestRegressor train score are: ",s3)

After RandomForestRegressor train score are:  0.9440432801793134

In [36]:
s3 = model_3.score(x_test,y_test)
print("After RandomForestRegressor train score are: ",s3)

After RandomForestRegressor train score are:  0.7393166325501512